### ISSUE TITLE
Getting 404 when saving tiles

### ISSUE THREAD

**Issue by lavebug** [robertomlsoares/leaflet-offline#8]
Trying to save tiles and get https://b.tile.openstreetmap.org/2/-1/0.png 404 any idea why?

**Comment by robertomlsoares** [comment]
Not sure, @lavebug. Could you provide more info? Like coordinates and zoom level.
It seems odd that you have a negative number in the url.

**Comment by lavebug** [comment]
I figured it out I was doing too many request so there is some kind of a limit.
